-------------------------------------------ADMIN1 TABLE--------------------------------------------------

create table admin1(
adminId number primary key,
mobileNumber number(10) not null,
userName varchar(30)not null,
password varchar(30) not null,
city varchar(50) not null);

insert into admin1(adminId,mobileNumber,userName,password,city)
values(101,'Karthik',9025513968,'Admin','Admin@1234','Chennai');

select adminId,mobileNumber,userName,password,city from admin1;
--drop table admin1;




-------------------------------------------LOCATION TABLE--------------------------------------------------

create table location(
stateId number(5) not null,
stateName varchar(30) not null,
locationId number(5)primary key,
city varchar(30) not null);

insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1001,'Ariyalur');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1002,'Chengalpattu');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1003,'Chennai');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1004,'Coimbatore');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1005,'Cuddalore');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1006,'Dharmapuri');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1007,'Dindigul');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1008,'Erode');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1009,'Kallakurichi');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1010,'Kancheepuram');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1011,'Karur');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1012,'Krishnagiri');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1013,'Kanyakumari');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1014,'Madurai');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1015,'Mayiladuthurai');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1016,'Nagapattinam');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1017,'Namakkal');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1018,'Perambalur');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1019,'Pudukottai');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1020,'Ramanathapuram');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1021,'Ranipet');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1022,'Salem');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1023,'Sivagangai');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1024,'Tenkasi');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1025,'Thanjavur');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1026,'Theni');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1027,'Thiruvallur');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1028,'Thiruvarur');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1029,'Tuticorin');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1030,'Trichy');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1031,'Thirunelveli');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1032,'Tirupathur');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1033,'Tiruppur');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1034,'Tiruvannamalai');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1035,'The Nilgiris');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1036,'Vellore');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1037,'Villupuram');
insert into location(stateId,stateName,locationId,city)values(10,'Tamilnadu',1038,'Virudhunagar');

select stateId,stateName,locationId,city from location;
--drop table location;




-------------------------------------------DONOR TABLE--------------------------------------------------

create table donor(
donorId number(5) generated by default on null as identity start with 1201 primary key,
donorName varchar(50) not null,
dob date not null,
weight varchar(10) not null,
gender varchar(25)not null,
bloodGroup varchar(20)not null,
mobileNumber number(15) unique,
email varchar(70)unique,
userName varchar(20) unique,
password varchar(30)not null,
donorRegisterDate timestamp,
address varchar(100) not null,
locationId number(5)not null,
constraint donor_locationid_fk foreign key(locationid) references location,
constraint donor_bloodgroup_fk foreign key(bloodGroup) references blood);

insert into donor(donorName,dob,weight,gender,bloodGroup,mobileNumber,email,userName,password,donorRegisterDate,address,locationId)
values('Gokul','05-04-2002','45(kg)','Male','A+',9578129250,'gokul@gmail.com','Goku1001','Gokul@1001',localtimestamp,'Cuddalore',1005);

select donorId,donorName,DOB,weight,gender,bloodGroup,mobileNumber,email,userName,password,donorRegisterDate,address,locationId from donor;
--drop table donor;


--Update donor set donorName='Selvam',weight='45kg',mobileNumber=9578129255,email='selvam@gmail.com',userName='selvam',password='Selvam12@',address='no21,West Street,Salem' where donorId= 1208;
-------------------------------------------BLOODBANK TABLE--------------------------------------------------

create table bloodBank(
bloodBankId number(5) generated by default on null as identity start with 1101,
bloodBankName varchar(60)not null,
contactNumber number(15)unique,
email varchar(70)unique,
userName varchar(30)unique,
password varchar(30)not null,
RegisterDate Date,
address varchar(100)not null,
locationid number(5)not null);

insert into bloodBank(bloodBankName,contactNumber,email,userName,password,RegisterDate,address)
values('SavingSpace',9445566771,'savingspace@gmail.com','Savi0001','Savi@0001',localtimestamp,'Ariyalur');

insert into bloodBank(bloodBankName,contactNumber,email,userName,password,RegisterDate,address)
values('Karthik BloodBank',9025513968,'karthikbloodbank@gmail.com','Kart0001','Kart@0001',localtimestamp,'Chennai');

select bloodBankId,bloodBankName,contactNumber,email,userName,password,RegisterDate,address,locationId from bloodBank order by registerdate desc;
--drop table bloodBank;

-------------------------------------------BLOOD STOCKS TABLE--------------------------------------------------

create table bloodStocks(
bloodBankId number(5)not null,
A_Positive number(3)not null,
A_Negative number(3)not null,
B_Positive number(3)not null,
B_Negative number(3)not null,
O_Positive number(3)not null,
O_Negative number(3)not null,
AB_Positive number(3)not null,
AB_Negative number(3)not null,
constraint bloodbank_stock_fk foreign key (bloodbankid) REFERENCES bloodbank);

insert into bloodstocks (bloodBankId,A_Positive,A_Negative,B_Positive,B_Negative,O_Positive,O_Negative,AB_Positive,AB_Negative) values (1110,100,80,100,70,100,60,100,90);

select bloodBankId,A_Positive,A_Negative,B_Positive,B_Negative,O_Positive,O_Negative,AB_Positive,AB_Negative from bloodstocks;
--drop table bloodstocks;

-------------------------------------------BLOOD TABLE--------------------------------------------------


create table blood(
bloodId number(5)not null,
bloodType VARCHAR(30) primary key);

insert into blood(bloodId,bloodType) values (11,'A+');
insert into blood(bloodId,bloodType) values (12,'A-');
insert into blood(bloodId,bloodType) values (13,'B+');
insert into blood(bloodId,bloodType) values (14,'B-');
insert into blood(bloodId,bloodType) values (15,'O+');
insert into blood(bloodId,bloodType) values (16,'O-');
insert into blood(bloodId,bloodType) values (17,'AB+');
insert into blood(bloodId,bloodType) values (18,'AB-');

select bloodId,bloodType from blood;
--drop table blood;

-------------------------------------------HOSPITAL TABLE--------------------------------------------------

create table hospital(
hospitalId number(5) generated by default on null as identity start with 2001 primary key,
hospitalName varchar(70)not null,
emailId varchar(70)unique,
userName varchar(20)unique,
password varchar(20)not null,
mobileNumber number(15)unique ,
address varchar(100)not null,
registerDate timestamp,
locationId number(5)not null);

insert into hospital(hospitalName,emailId,userName,password,mobileNumber,address,registerDate,locationId) values ('Sankara Hospital','sankarahospital@gmail.com','Sank2001','Sank@2001',9441111222,'Coimbatore',localtimestamp,1103);
insert into hospital(hospitalName,emailId,userName,password,mobileNumber,address,registerDate,locationId) values ('Sankaran Hospital','sankaranhospital@gmail.com','Sankaran2001','Sankaran@2001',9441111221,'Dindigul',localtimestamp,1108);

select hospitalId,hospitalName,emailId,userName,password,mobileNumber,address,registerDate,locationId from hospital;
--drop table hospital;

-------------------------------------------SEEKER TABLE--------------------------------------------------

create table seeker(
seekerId number(5) generated by default on null as identity start with 501 primary key,
seekerName varchar(50)not null,
mobileNumber number(15)unique,
gender varchar(25)not null,
userName varchar(20)unique,
password varchar(20)not null,
address varchar(100)not null,
registerDate timestamp,
locationId number(5)not null,
constraint seeker_locationid_fk foreign key(locationid) references location);

insert into seeker(seekerName,mobileNumber,gender,userName,password,address,registerDate,locationId)values('Nithin',1234554321,'Male','Nith0501','Nith@0501','23,East Street,Ariyalur',localtimestamp,1001);

select seekerId,seekerName,mobileNumber,gender,userName,password,address,registerDate,locationId from seeker;
--drop table seeker;

-------------------------------------------DONATE TABLE--------------------------------------------------

create table donate(
donateId number(5) generated by default on null as identity start with 101,
donorId number(5)not null,
donatorName varchar(30) not null,
quantity number(6)not null,
mobilNumber number(15)not null,
bloodGroup varchar(5)not null,
donateDate Date not null,
bloodBankId number(5)not null,
constraint donate_donorId_fk foreign key(donorId) references donor,
constraint bloodbank_donate_fk foreign key (bloodbankid) REFERENCES bloodbank,
constraint donate_bloodgroup_fk foreign key(bloodGroup) references blood);

insert into donate(donorId,quantity,mobilNumber,bloodGroup,donateDate,bloodBankId)values(1201,2,9578129250,'A+',localtimestamp,1105);

select donateId,donorId,donatorName,quantity,mobilNumber,bloodGroup,donateDate,bloodBankId from donate;
--drop table donate;


-------------------------------------------BLOOD REQUEST TABLE--------------------------------------------------

create table bloodRequest(
requestId number(5) generated by default on null as identity start with 3001,
requestingId number(5) not null,
requestorType varchar(20)not null,
requestDate timestamp,
bloodGroup varchar(10)not null,
quantity number(5)not null,
requestLocation varchar(100)not null,
requestMobileNo number(15)not null,
bloodBankId number(5) not null,
status varchar(50) not null,
constraint bloodbank_Request_fk foreign key (bloodbankid) REFERENCES bloodbank,
constraint hospital_bloodgroup_fk foreign key(bloodGroup) references blood);

insert into bloodRequest (requestingId,requestorType,requestDate,bloodGroup,quantity,requestLocation,requestMobileNo,bloodBankId,status) values (2001,'Hospital',localtimestamp,'B+',2,'Ariyalur',9620419880,1101,'Pending');
insert into bloodRequest (requestingId,requestorType,requestDate,bloodGroup,quantity,requestLocation,requestMobileNo,bloodBankId,status) values (501,'Seeker',localtimestamp,'B+',2,'Ariyalur',1234554321,1101,'Pending');

select * from bloodRequest;
--drop table bloodrequest;
--------------------------------------------------------------------------------------------------------






alter table bloodbank modify (locationid number(5),constraint hospital_locationid_fk foreign key(locationid) references location);
Update hospital set locationid=1004 where hospitalid= 2001;
Update donate set donatorNAME='Gokul' where donorid= 1201;
Update hospital set locationid=1006 where hospitalid= 2003;
alter table donor modify (gender varchar(25));
alter table bloodbank drop column bloodbankid;
alter table hospital add locationId number(5);
Select donorId,donorName,DOB,weight,gender,bloodGroup,mobileNumber,email,userName,donorRegisterDate,address,locationId from donor where mobilenumber not in (Select mobilnumber from Donate) order by Donorid asc;
Select donateId,quantity,bloodGroup,bloodBankId from donate where mobilNumber =9578129251;
select count(*) from donor where bloodBankId=1101;
Select requestId,hospitalId,requestDate,bloodGroup,quantity,reqLocation,reqMobileNo,bloodBankId,status from HospitalRequest hosp Where status = 'Pending' union Select requestId,seekerId,requestDate,bloodGroup,quantity,reqLocation,reqMobileNo,bloodBankId,status from seekerRequest where status = 'Pending';
select count(status) from hospitalRequest where status= 'Approved';
update bloodBank set A_Positive =A_Positive+10, A_Negative =A_Negative+10, B_Positive =B_Positive+10, B_Negative =B_Negative+10, O_Positive =O_Positive+10, O_Negative =O_Negative+10, AB_Positive =AB_Positive+10, AB_Negative =AB_Negative+10 where bloodBankId=1103;
Select donorId,donorName,dob,weight,gender,bloodGroup,mobileNumber,email,userName,password,donorRegisterDate,address,locationId from donor where mobileNumber not in (Select mobilNumber from Donate) order by Donorid asc;	
select hospitalId,hospitalName,emailId,userName,mobileNumber,address,registerDate from hospital where address = 'Chennai';
select count(*) from donor where Address = 'Ariyalur';
select requestId,requestingId,requestorType,requestDate,bloodGroup,quantity,requestLocation,requestMobileNo,bloodBankId,status from bloodRequest where status='Pending' and bloodBankId=1101 order by requestId desc; 
select count(status) from bloodRequest where bloodBankId = 1105;
select seekerId,seekerName,mobileNumber,gender,userName,address,registerDate,locationId from seeker where locationId = 1001 order by seekerId desc;
select bb.bloodbankid,bb.bloodbankname,bb.contactNumber,bb.email,bb.username,bb.registerdate,bb.address,bb.locationid,bs.a_positive,bs.a_negative,bs.b_positive,bs.b_negative,bs.o_positive,bs.o_negative,bs.ab_positive,bs.ab_negative from bloodBank bb,bloodstocks bs where  bb.bloodBankid = bs.bloodBankid;
select bloodBankId,bloodBankName,contactNumber,email,userName,password,RegisterDate,address,locationid from bloodBank order by registerdate desc;
select bloodBankId,A_Positive,A_Negative,B_Positive,B_Negative,O_Positive,O_Negative,AB_Positive,AB_Negative from bloodstocks;
select hospitalId,hospitalName,emailId,userName,mobileNumber,address,registerDate,locationId from hospital where locationId= 1005 order by hospitalId desc ;
select count(*) from donor where locationId = 1001;
select donorId from donate;
alter table bloodRequest modify (requestMobileNo number(15));
update seeker set password ='Hema@1234'  where seekerid=562;
Select mobileNumber from seeker where mobileNumber = 7019978756;
select donatedate from donate where donorId = 1281;










select * from admin1;
select * from location;
select * from donor; 
select * from bloodBank;
select * from bloodstocks;
select * from blood;
select * from hospital;
select * from seeker;
select * from  donate;
select * from bloodrequest;

commit;     
rollback;